### ISSUE TITLE
ssh: handshake failed: knownhosts: key mismatch

### ISSUE THREAD

**Issue by APoniatowski** [APoniatowski/GoSSH#10]
```
ssh: handshake failed: knownhosts: key mismatch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f1b61]

goroutine 8 [running]:
github.com/APoniatowski/GoSSH/sshlib.connectAndRun(0xc0000b58a0, 0xc00001cb10, 0xd, 0xc000016840, 0x1a, 0xc00001cb38, 0x8, 0x0, 0x0, 0xc000016900, ...)
        C:/dev/golang/GoSSH/sshlib/sshlib.go:78 +0x4b1
created by github.com/APoniatowski/GoSSH/sshlib.RunAllServers
        C:/dev/golang/GoSSH/sshlib/sshlib.go:271 +0x463
```

This will need a quick patch...

**Comment by APoniatowski** [comment]
possible root cause:  there are multiple entries in the known_hosts file (in prod environment) which might be causing these issues.  I cannot clear out the known_hosts file and add them again. So I will have to test it out in my test environment (will test master and Dev branches and decide if a revert is needed on the Dev branch)
I will possibly make some changes to the seq option, to add servers to the known_hosts file and add prints to run seq first, to add entries... or create a separate option entirely.

**Comment by APoniatowski** [comment]
ran in test environment. still fails with key mismatch. I cleared my known_hosts file, ssh'd manually to them (with hostname and FQDN) and there is still a key mismatch. I might have to scrap the known_hosts/FixedHostkeys path/method

**Comment by APoniatowski** [comment]
removed from milestone, as this is a separate issue that is not a complete blocker
